// KUBO KARTS v3 - strings for the redesigned menus (EN + FA).
import { extendLang } from '../core/lang';

extendLang({
  playSub: 'Career · Quick · Online', itemsSub: '15 power-ups', shopSub: 'Gems & coins',
  seasons: 'SEASONS', seasonsSub: 'Career campaign', dailyShort: 'DAILY',
  chooseModeSub: 'Pick how you want to race', maps: 'maps', upTo6: 'Up to 6 players',
  season: 'SEASON', seasonLocked: 'Finish the previous season to unlock',
  season_0: 'Road Begins', season_0_d: 'Valleys, castles and desert heat — learn the lines.',
  season_1: 'Fire & Ice', season_1_d: 'Frozen peaks, a live volcano and deep crystal caves.',
  season_2: 'Skies & Streets', season_2_d: 'Floating islands and neon city nights.',
  season_3: 'Lost Realms', season_3_d: 'Block cities, ancient ruins and the wild canopy.',
  season_4: 'Mega Finale', season_4_d: 'One giant ramp. Pure speed. Only legends finish.',
  needPrev: 'Earn a star on the previous stage first',
  quickSub: 'Pick a track and go', tagNight: 'Night', tagHazard: 'Hazards', tagJumps: 'Jumps', oneLap: '1 lap',
  powerUps: 'POWER-UPS', powerUpsOn: 'power-ups on', powerUpsOff: 'power-ups off',
  itemsSub2: 'Guide & on/off switches', powerUpsModeSub: 'Item boxes in this mode',
  powerUpsMpNote: 'Multiplayer uses the host\'s own power-up list.',
  powerUpsPick: 'Choose power-ups', powerUpsPickSub: 'Turn single power-ups on/off',
  cat_attack: 'ATTACK', cat_trap: 'TRAPS', cat_defense: 'DEFENSE', cat_util: 'UTILITY',
  toman: 'Toman', payTitle: 'Payment', payFailed: 'Payment was not completed',
  payNotConnected: 'The payment gateway is not connected yet. Purchases open very soon.',
  tag_best: 'BEST VALUE', tag_hot: 'POPULAR', tag_first: 'ONE-TIME',
  pk_gems_s: 'Gem Pouch', pk_gems_m: 'Gem Stack', pk_gems_l: 'Gem Chest', pk_gems_xl: 'Gem Vault',
  pk_coins_s: 'Coin Bag', pk_coins_m: 'Coin Sack', pk_coins_l: 'Coin Truck',
  pk_parts_s: 'Parts Box', pk_parts_m: 'Parts Crate',
  pk_rookie: 'Rookie Pack', pk_rookie_d: 'One-time starter deal',
  pk_pro: 'Pro Racer Bundle', pk_pro_d: 'Everything you need to max a car',
  gemsTitle: 'GEMS', coinsTitle: 'COINS', partsTitle: 'PARTS',
  exchange: 'EXCHANGE', exchangeSub: 'pay with gems',
  shopLegal: 'Prices in Toman. Purchased currency is added to your account instantly after a verified payment.',
  dailySub: '7-day streak', bigPrize: 'MEGA',
  challengesSub: 'Daily tasks & achievements', achievements: 'ACHIEVEMENTS',
  dailyTaskSub: 'Resets at midnight', achDone: 'Achievement reward claimed',
  ac_race10: 'Warmed Up', ac_race10_d: 'Finish 10 races',
  ac_race50: 'Road Veteran', ac_race50_d: 'Finish 50 races',
  ac_win5: 'Podium Habit', ac_win5_d: 'Win 5 races',
  ac_win25: 'Champion', ac_win25_d: 'Win 25 races',
  ac_star30: 'Star Collector', ac_star30_d: 'Earn 30 stars',
  ac_star90: 'Star Hunter', ac_star90_d: 'Earn 90 stars',
  ac_star180: 'Perfect Career', ac_star180_d: 'Earn every star',
  ac_clear20: 'Explorer', ac_clear20_d: 'Clear 20 stages',
  ac_cars5: 'Garage Starter', ac_cars5_d: 'Own 5 cars',
  ac_carsAll: 'Full Garage', ac_carsAll_d: 'Own every car',
  ac_chars5: 'Crew Up', ac_chars5_d: 'Unlock 5 racers',
  ac_charsAll: 'Full Roster', ac_charsAll_d: 'Unlock every racer',
  ac_lvl10: 'Rising Star', ac_lvl10_d: 'Reach player level 10',
  ac_mp1: 'Local Legend', ac_mp1_d: 'Win a multiplayer race',
  profileSub: 'Your racing career', myRide: 'MY RIDE', editName: 'Edit name',
  statsTitle: 'STATS', collection: 'COLLECTION', badges: 'BADGES', stagesCleared: 'Stages cleared',
  st_races: 'Races', st_wins: 'Wins', st_winrate: 'Win rate', st_stars: 'Stars', st_drifts: 'Drifts',
  st_mpwins: 'Online wins', st_coins: 'Coins earned', st_time: 'Play time', hShort: 'h', mShort: 'm',
  secGraphics: 'DISPLAY', secAudio: 'AUDIO', secControls: 'CONTROLS', error: 'Error',
  lobbyPlayers: 'PLAYERS', lobbyYou: 'YOU', hostSetup: 'SERVER SETUP', yourRide: 'YOUR RIDE',
  garageSub: 'Buy, paint and tune', charsSub: 'Pick your racer', mpSub: 'Local Wi-Fi rooms',
}, {
  playSub: 'دوران حرفه‌ای · سریع · آنلاین', itemsSub: '۱۵ قدرت', shopSub: 'جم و سکه',
  seasons: 'فصل‌ها', seasonsSub: 'مسابقات دوران حرفه‌ای', dailyShort: 'روزانه',
  chooseModeSub: 'انتخاب کن چطور مسابقه بدی', maps: 'پیست', upTo6: 'تا ۶ بازیکن',
  season: 'فصل', seasonLocked: 'برای باز شدن، فصل قبل را تمام کن',
  season_0: 'آغاز جاده', season_0_d: 'دره، قلعه و گرمای کویر — خط‌های مسابقه را یاد بگیر.',
  season_1: 'یخ و آتش', season_1_d: 'قله‌های یخ‌زده، آتشفشان زنده و غارهای بلوری.',
  season_2: 'آسمان و خیابان', season_2_d: 'جزیره‌های شناور و شب‌های نئونی شهر.',
  season_3: 'قلمروهای گمشده', season_3_d: 'شهر بلوکی، ویرانه‌های باستانی و جنگل وحشی.',
  season_4: 'فینال بزرگ', season_4_d: 'یک رمپ غول‌پیکر. سرعت خالص. فقط اسطوره‌ها تمامش می‌کنند.',
  needPrev: 'اول از مرحلهٔ قبل ستاره بگیر',
  quickSub: 'پیست را انتخاب کن و برو', tagNight: 'شب', tagHazard: 'خطر', tagJumps: 'پرش', oneLap: '۱ دور',
  powerUps: 'قدرت‌ها', powerUpsOn: 'قدرت‌ها روشن', powerUpsOff: 'قدرت‌ها خاموش',
  itemsSub2: 'راهنما و روشن/خاموش', powerUpsModeSub: 'جعبه‌های قدرت در این حالت',
  powerUpsMpNote: 'در چندنفره لیست قدرت‌ها را میزبان انتخاب می‌کند.',
  powerUpsPick: 'انتخاب قدرت‌ها', powerUpsPickSub: 'هر قدرت را جدا روشن/خاموش کن',
  cat_attack: 'حمله', cat_trap: 'تله‌ها', cat_defense: 'دفاع', cat_util: 'کمکی',
  toman: 'تومان', payTitle: 'پرداخت', payFailed: 'پرداخت انجام نشد',
  payNotConnected: 'درگاه پرداخت هنوز وصل نشده است. خرید به‌زودی فعال می‌شود.',
  tag_best: 'به‌صرفه‌ترین', tag_hot: 'محبوب', tag_first: 'یک‌بار',
  pk_gems_s: 'کیسهٔ جم', pk_gems_m: 'دستهٔ جم', pk_gems_l: 'صندوق جم', pk_gems_xl: 'گاوصندوق جم',
  pk_coins_s: 'کیسهٔ سکه', pk_coins_m: 'گونی سکه', pk_coins_l: 'کامیون سکه',
  pk_parts_s: 'جعبهٔ قطعات', pk_parts_m: 'صندوق قطعات',
  pk_rookie: 'پک تازه‌کار', pk_rookie_d: 'پیشنهاد شروع — فقط یک بار',
  pk_pro: 'باندل راننده حرفه‌ای', pk_pro_d: 'هرچی برای فول کردن یک ماشین لازم داری',
  gemsTitle: 'جم', coinsTitle: 'سکه', partsTitle: 'قطعات',
  exchange: 'تبدیل', exchangeSub: 'پرداخت با جم',
  shopLegal: 'قیمت‌ها به تومان است. ارز خریداری‌شده بلافاصله بعد از تأیید پرداخت به حسابت اضافه می‌شود.',
  dailySub: 'جایزهٔ ۷ روز پشت سر هم', bigPrize: 'جایزه ویژه',
  challengesSub: 'کارهای روزانه و دستاوردها', achievements: 'دستاوردها',
  dailyTaskSub: 'نیمه‌شب ریست می‌شود', achDone: 'جایزهٔ دستاورد دریافت شد',
  ac_race10: 'گرم شدی', ac_race10_d: '۱۰ مسابقه را تمام کن',
  ac_race50: 'کهنه‌کار جاده', ac_race50_d: '۵۰ مسابقه را تمام کن',
  ac_win5: 'عادت به سکو', ac_win5_d: '۵ مسابقه ببر',
  ac_win25: 'قهرمان', ac_win25_d: '۲۵ مسابقه ببر',
  ac_star30: 'ستاره‌جمع‌کن', ac_star30_d: '۳۰ ستاره بگیر',
  ac_star90: 'شکارچی ستاره', ac_star90_d: '۹۰ ستاره بگیر',
  ac_star180: 'دوران بی‌نقص', ac_star180_d: 'همهٔ ستاره‌ها را بگیر',
  ac_clear20: 'کاشف', ac_clear20_d: '۲۰ مرحله را رد کن',
  ac_cars5: 'گاراژ نوپا', ac_cars5_d: '۵ ماشین داشته باش',
  ac_carsAll: 'گاراژ کامل', ac_carsAll_d: 'همهٔ ماشین‌ها را داشته باش',
  ac_chars5: 'تیم‌سازی', ac_chars5_d: '۵ شخصیت باز کن',
  ac_charsAll: 'تیم کامل', ac_charsAll_d: 'همهٔ شخصیت‌ها را باز کن',
  ac_lvl10: 'ستارهٔ در حال طلوع', ac_lvl10_d: 'به سطح ۱۰ برس',
  ac_mp1: 'اسطورهٔ محله', ac_mp1_d: 'یک مسابقهٔ چندنفره ببر',
  profileSub: 'کارنامهٔ مسابقه‌ات', myRide: 'ماشین من', editName: 'تغییر نام',
  statsTitle: 'آمار', collection: 'کلکسیون', badges: 'نشان‌ها', stagesCleared: 'مراحل ردشده',
  st_races: 'مسابقه', st_wins: 'برد', st_winrate: 'درصد برد', st_stars: 'ستاره', st_drifts: 'دریفت',
  st_mpwins: 'برد آنلاین', st_coins: 'سکهٔ کسب‌شده', st_time: 'زمان بازی', hShort: 'س', mShort: 'د',
  secGraphics: 'نمایش', secAudio: 'صدا', secControls: 'کنترل', error: 'خطا',
  lobbyPlayers: 'بازیکن‌ها', lobbyYou: 'تو', hostSetup: 'تنظیمات سرور', yourRide: 'ماشین تو',
  garageSub: 'خرید، رنگ و تیونینگ', charsSub: 'راننده‌ات را انتخاب کن', mpSub: 'اتاق‌های وای‌فای محلی',
});
