// KUBO KARTS - i18n: English + Persian (Farsi)
// Persian is the DEFAULT language (user request). All UI strings for every
// screen live here; switching language triggers a full UI rebuild.

const EN: Record<string, string> = {
  // Generic
  ok: 'OK', cancel: 'Cancel', back: 'Back', close: 'Close', on: 'ON', off: 'OFF',
  locked: 'LOCKED', owned: 'OWNED', buy: 'BUY', equip: 'EQUIP', equipped: 'EQUIPPED',
  select: 'SELECT', selected: 'SELECTED', free: 'FREE', new: 'NEW!', max: 'MAX',
  // Menu
  play: 'PLAY', garage: 'GARAGE', characters: 'CHARACTERS', items: 'ITEMS',
  shop: 'SHOP', settings: 'SETTINGS', mapSelection: 'MAP SELECTION',
  challenges: 'CHALLENGES', dailyRewards: 'DAILY REWARDS', news: 'NEWS',
  multiplayer: 'MULTIPLAYER', career: 'CAREER', quickRace: 'QUICK RACE',
  level: 'Level', xp: 'XP',
  raceExplore: 'RACE • EXPLORE • COLLECT',
  tapToStart: 'TAP TO START',
  // Modes
  chooseMode: 'CHOOSE MODE', careerDesc: '60 hand-crafted challenges',
  quickDesc: 'Instant race, any map', mpDesc: 'Play with friends on Wi-Fi',
  // Level select
  selectLevel: 'SELECT LEVEL', laps: 'Laps', difficulty: 'DIFFICULTY',
  objective: 'OBJECTIVE', best: 'BEST', stars: 'STARS',
  easy: 'EASY', normal: 'NORMAL', hard: 'HARD', extreme: 'EXTREME',
  special: 'SPECIAL', boss: 'BOSS',
  // Objectives
  obj_finish1: 'Finish 1st', obj_finish3: 'Finish in Top 3', obj_time: '{0}s — beat the time!',
  obj_drift: 'Drift for {0}s total', obj_items: 'Use {0} power-ups',
  obj_survive: 'Survive the hazards', obj_nofall: 'Win without falling', obj_clean: 'Win without crashing',
  // Level modifiers (each stage mixes its own rule-set)
  mod_none: 'Standard rules',
  mod_night: 'NIGHT RACE', mod_night_d: 'Headlights on — the world goes dark',
  mod_lowgrip: 'ICE GRIP', mod_lowgrip_d: 'Slippery tarmac — brake early!',
  mod_turbostart: 'TURBO START', mod_turbostart_d: 'Free boost the moment the race begins',
  mod_itemstorm: 'ITEM STORM', mod_itemstorm_d: 'Double item boxes everywhere',
  mod_noitems: 'PURE SKILL', mod_noitems_d: 'No power-ups — just racing',
  mod_fog: 'THICK FOG', mod_fog_d: 'Low visibility — trust the minimap',
  mod_boss: 'BOSS RACE', mod_boss_d: 'A rival with a maxed-out machine',
  mod_gems: 'GEM RUN', mod_gems_d: 'Bonus gems for finishing top 3',
  mod_veteran: 'VETERAN AI', mod_veteran_d: 'The AI is angry today',
  mod_hazard: 'HAZARD ZONE', mod_hazard_d: 'Track hazards are everywhere',
  // HUD
  pos: 'POS', lap: 'LAP', wrongWay: 'WRONG WAY!', finalLap: 'FINAL LAP!',
  go: 'GO!', countdown3: '3', countdown2: '2', countdown1: '1',
  paused: 'PAUSED', resume: 'RESUME', restart: 'RESTART', quit: 'QUIT RACE',
  drift: 'DRIFT', gas: 'GAS', brake: 'BRAKE',
  // Results
  raceFinished: 'RACE FINISHED', youWin: 'VICTORY!', youLose: 'RACE OVER',
  rewards: 'REWARDS', coins: 'COINS', gems: 'GEMS', parts: 'PARTS',
  nextRace: 'NEXT RACE', replay: 'REPLAY', toMenu: 'MENU',
  newRecord: 'NEW RECORD!', missionComplete: 'MISSION COMPLETE!', missionFailed: 'MISSION FAILED',
  bestTime: 'Best Time', time: 'TIME', retry: 'TRY AGAIN',
  // Garage
  stats: 'STATS', customize: 'CUSTOMIZE', cars: 'CARS',
  speed: 'SPEED', accel: 'ACCEL', handling: 'HANDLING', driftStat: 'DRIFT',
  weight: 'WEIGHT', boost: 'BOOST', defense: 'DEFENSE',
  paint: 'PAINT', wheels: 'WHEELS', spoiler: 'SPOILER', decals: 'DECALS',
  exhaust: 'EXHAUST', boostFx: 'BOOST FX', upgrade: 'UPGRADE',
  underglow: 'UNDERGLOW', underglowHint: 'Neon light under your car — NIGHT ONLY (auto-on in the dark) • every car has it; pick a color or leave it on AUTO',
  none: 'OFF',
  upgradeCost: 'UPGRADE ({0})', maxed: 'FULLY UPGRADED',
  // Workshop (car tuning — big garage update)
  workshop: 'WORKSHOP', workshopSub: 'Tune your machine part by part',
  w_engine: 'ENGINE', w_engine_d: 'Top speed',
  w_turbo: 'TURBO', w_turbo_d: 'Boost power & duration',
  w_tires: 'TIRES', w_tires_d: 'Grip & handling',
  w_driftkit: 'DRIFT KIT', w_driftkit_d: 'Drift charge speed',
  w_armor: 'ARMOR', w_armor_d: 'Weight & knock-back defense',
  w_buildLvl: 'BUILD LV', w_next: 'Next', w_unlockHint: 'Reach Level {0} to tune further',
  buildBonus: 'Full build bonus: +4% all stats',
  // Characters
  charSelect: 'CHARACTERS', ability: 'SPECIAL TRAIT',
  // Shop
  shopTitle: 'SHOP', dailyOffers: 'DAILY OFFERS', bundles: 'BUNDLES',
  soldOut: 'SOLD OUT', notEnough: 'NOT ENOUGH', purchased: 'PURCHASED!',
  bundle_starter: 'Starter Pack', bundle_starter_d: '8 Parts + 10 Gems',
  bundle_parts: 'Parts Crate', bundle_parts_d: '15 upgrade parts',
  bundle_gem: 'Gem Vault', bundle_gem_d: '5,000 coins + 10 parts',
  // Daily
  claim: 'CLAIM', claimed: 'CLAIMED', comeBack: 'Come back tomorrow!',
  day: 'DAY', nextReward: 'Next reward in',
  // Challenges
  dailyTasks: 'DAILY TASKS', rewards2: 'REWARDS', collect: 'CLAIM ALL',
  ch_win1: 'Win a race', ch_win3: 'Win 3 races', ch_drift20: 'Drift for 20 seconds',
  ch_coins50: 'Earn 750 coins (any races)', ch_items5: 'Use 5 power-ups', ch_race2: 'Finish 2 races',
  ch_stars2: 'Earn 2 stars', ch_mp1: 'Play a multiplayer race', ch_jump10: 'Do 10 jumps',
  // Multiplayer
  mpTitle: 'LOCAL WI-FI MULTIPLAYER', createRoom: 'CREATE ROOM', joinRoom: 'JOIN ROOM',
  roomCode: 'ROOM CODE', enterCode: 'Enter room code...', join: 'JOIN',
  players: 'PLAYERS', ready: 'READY', notReady: 'NOT READY', startRace: 'START RACE',
  waitingHost: 'Waiting for host to start...', connected: 'Connected!',
  connecting: 'Connecting...', connectionLost: 'Connection lost!',
  hostLeft: 'Host left - new host: {0}', playerJoined: '{0} joined!', playerLeft: '{0} left',
  mpReconnecting: 'Connection lost — reconnecting', mpReconnected: 'Reconnected!', mpPeerLost: '{0} lost connection…', mpPeerBack: '{0} is back',
  chooseTrack: 'CHOOSE TRACK', yourIp: 'Share this code with friends',
  mpNeedsServer: 'Multiplayer requires the game server. See docs.',
  scanning: 'Looking for room...', youAreHost: 'You are the host',
  raceInProgress: 'Race already in progress',
  // Settings
  settingsTitle: 'SETTINGS', graphics: 'GRAPHICS', sound: 'SOUND',
  music: 'MUSIC', sfx: 'SFX', master: 'MASTER', vibration: 'VIBRATION',
  sensitivity: 'STEERING SENSITIVITY', controlLayout: 'STEERING MODE', wheelSize: 'WHEEL SIZE',
  wheel: 'WHEEL', buttons: 'BUTTONS', tilt: 'TILT',
  language: 'LANGUAGE', data: 'DATA', showFps: 'SHOW FPS',
  exportData: 'EXPORT SAVE', importData: 'IMPORT SAVE', resetData: 'RESET PROGRESS',
  resetConfirm: 'Erase ALL progress? This cannot be undone!',
  low: 'LOW', medium: 'MEDIUM', high: 'HIGH', ultra: 'ULTRA',
  // Items
  item_boost: 'NITRO', item_shield: 'SHIELD', item_rocket: 'ROCKET', item_lightning: 'LIGHTNING',
  item_ice: 'ICE SHOT', item_trap: 'OIL SLICK', item_mine: 'MINE', item_magnet: 'MAGNET',
  item_emp: 'SHOCKWAVE', item_giant: 'MONSTER MODE', item_ghost: 'PHANTOM', item_jump: 'SPRING MINE',
  // item descriptions (v1.9: Persian translations — the guide was EN-only)
  item_boost_d: 'Instant turbo burst — the exhaust roars and you launch forward.',
  item_shield_d: 'A blue energy bubble. Blocks the next hit — and DEFLECTS an incoming missile.',
  item_rocket_d: 'A homing missile that hunts the racer ahead. Listen for the beeps — if YOU hear them, it is coming for YOU! Hold LOOK BACK to fire it at whoever is behind.',
  item_lightning_d: 'BLUE STORM: three giant electric zones materialize one by one (1… 2… 3…) AHEAD of the first-place racer, each with rolling thunder. Touch one and it discharges — HUGE damage — then vanishes. Zones expire after 12s.',
  item_ice_d: 'A frozen shard that hunts the racer in front and locks them in an ice cube.',
  item_trap_d: 'Drops a slippery oil slick behind you. Rivals who drive over it spin out.',
  item_mine_d: 'Plants a MINE behind your car. It blows up ANYONE who drives over it — even YOU. Watch the blinking red light!',
  item_magnet_d: 'Pulls faraway item boxes toward you • pays +60 coins at the finish. Its field also DEFLECTS missiles!',
  item_emp_d: 'A purple shockwave that stalls every racer close to you.',
  item_giant_d: 'Monster mode: you grow huge, plow every rival off the road, fire 2x-size weapons and TAKE HALF DAMAGE.',
  item_ghost_d: 'Phase out for 5 seconds: missiles, mines and lightning pass right through you, and you drive through rivals.',
  item_jump_d: 'Plants a wooden floor plate behind you. Whoever drives over it trips a hidden spring: launched sky-high with heavy damage. It even catches you once armed.',
  item_tnt: 'TNT', item_banana: 'BANANA PEEL', item_minecart: 'MINECART',
  item_tnt_d: 'Drops a LIT TNT block behind you. The fuse keeps burning and it EXPLODES the moment a car reaches it. Big blast, knocks racers into the air.',
  item_banana_d: 'Drops a banana peel on the road. The next racer who drives over it slips and spins out.',
  item_minecart_d: 'Summons a runaway minecart that rolls down the track on its own rails, hunts the nearest racer ahead and throws them off the road.',
  breakdown: 'BREAKDOWN!', repaired: 'Repaired — back to the race!',
  carTier: 'RANK',
  carWrecked: 'WRECKED! Fixing the car…',
  missileWarn: 'MISSILE INCOMING!',
  // v1.10 HUD layout editor (user: "یک گزینه داخل تنظیمات که کاربر بتونه خودش
  // تمام دکمه‌ها و چینش‌های داخل صفحه انجام بده… و بتونه بزرگ و کوچیک کنه")
  hudLayout: 'BUTTON LAYOUT',
  hudLayoutSub: 'Move & resize every on-screen button',
  hudLayoutEdit: 'EDIT LAYOUT',
  hudLayoutHint: 'Drag a button to move it — use ＋ / − to resize',
  hudLayoutReset: 'RESET',
  hudLayoutDone: 'DONE',
  hudLayoutSaved: 'Layout saved',
  // v1.22 HUD presets (user: "یه نسخه دیگه درست کنی که ساده باشه … به طور دیفالت
  // اون باشه و بشه انتخاب کرد یکی از اون دو نسخه" + "سرعت سنجه هم بشه جاشو
  // ویرایش کرد مثل بقیه چیزها")
  hudPreset: 'HUD LAYOUT',
  hudPresetSub: 'Simple packs everything tighter — speedometer under the item slots',
  hudSimple: 'SIMPLE',
  hudNormal: 'CLASSIC',
  hudSimpleToast: 'Simple layout (default)',
  hudNormalToast: 'Classic layout',
  layoutPedals: 'GAS / BRAKE', layoutSteer: 'LEFT / RIGHT', layoutWheel: 'STEERING ZONE',
  layoutDrift: 'DRIFT', layoutSlots: 'POWER-UPS', layoutHearts: 'HEALTH',
  layoutLook: 'LOOK BACK', layoutPause: 'PAUSE', layoutMeter: 'DRIFT METER',
  layoutSpeedo: 'SPEEDOMETER',
  // v1.11 per-button layout entries (user: "هر دکمه جدا بشه تغییر مکان یا تغییر سایز")
  layoutGas: 'GAS', layoutBrake: 'BRAKE', layoutLeft: 'LEFT ◀', layoutRight: 'RIGHT ▶',
  layoutSlot1: 'POWER-UP 1', layoutSlot2: 'POWER-UP 2', layoutSlot3: 'POWER-UP 3',
  layoutLight: 'HEADLIGHT',
  // v1.11 named sound list (user: "برای همه صداهای بازی اسم بزاری")
  soundList: 'SOUND LIST',
  soundListSub: 'Every sound in the game, by name — tap to preview',
  glowAuto: 'AUTO (default neon)',
  lobbyCustomize: 'CUSTOMIZE CAR', lobbyHintHostCars: 'You can also use the HOST\'s unlocked cars here',
  // World / theme names
  theme_grass: 'Sunny Valley', theme_castle: 'Stone Keep', theme_desert: 'Sunbaked Dunes',
  theme_snow: 'Frostbite Peaks', theme_volcano: 'Ember Core', theme_cave: 'Echo Caverns',
  theme_sky: 'Sky Gardens', theme_city: 'Neon City', theme_crashcity: 'Crash City', theme_ruins: 'Lost Ruins',
  theme_jungle: 'Wild Jungle', theme_mccity: 'BlockTech City', theme_megaramp: 'Mega Ramp', theme_candy: 'Candy Kingdom', theme_galaxy: 'Star Galaxy', theme_dragon: 'Dragon Temple', theme_royal: 'Royal Gold City',
  // Car classes
  cls_balanced: 'BALANCED', cls_speed: 'SPEED', cls_drift: 'DRIFT',
  cls_heavy: 'HEAVY', cls_accel: 'ACCEL',
  carUnlockToast: '{0} is now available in the Garage!',
  carReqLevel: 'Unlocks at Level {0}',
  // Misc
  loading: 'LOADING', tip: 'TIP', version: 'VERSION',
  generatingTrack: 'GENERATING TRACK…', buildingWorld: 'BUILDING WORLD…', paintingSky: 'PAINTING SKY…',
  driftBoostReady: 'MINI-TURBO!', ultraTurbo: 'ULTRA TURBO!',
  recovered: 'RECOVERED!',
  invertSteer: 'INVERT STEERING',
  autoGas: 'AUTO GAS',
  coinsRace: 'COINS', position: 'POSITION',
  unlockAtLevel: 'Unlocks at Level {0}', unlockLevelN: 'Reach Level {0} to buy',
  beat: 'BEAT', sec: 's', no: 'No', yes: 'Yes',
  howToPlay: 'HOW TO PLAY', controlsInfo: 'Steer with the wheel • Hold GAS to accelerate • Hold DRIFT in corners to charge a mini-turbo • Tap the item button to use power-ups',
  profile: 'PROFILE', editName: 'TAP TO EDIT NAME',
  winStreak: 'WIN STREAK', races: 'RACES', wins: 'WINS',
  worldRecord: 'PERSONAL BEST', finish: 'FINISH',
  newsTitle: 'LATEST NEWS',
  newsBody: 'Season 2 is live! 60 re-crafted stages with night races, ice grip, item storms and boss rivals. 6 new sports cars wait in the garage — level up to unlock them all!',
  eventTitle: 'SEASON 2 EVENT', eventDesc: 'Sports Car Season! New rides, new stage rules, bigger tracks.',
  bootSub: 'VOXEL ARCADE RACING',
  bootTip1: 'Hold DRIFT in corners to charge a MINI-TURBO!',
  bootTip2: 'Gold sparks = ULTRA TURBO. Release drift to fire!',
  bootTip3: 'Players behind get stronger power-ups. Fair & fun!',
  bootTip4: 'Tune your car in the Workshop for extra speed!',
  bootTip5: 'Play friends over local Wi-Fi — up to 6 racers!',
  start: 'START',
  // Multiplayer v2 (IP-based Wi-Fi rooms)
  becomeServer: 'BECOME SERVER', becomeServerSub: 'Pick map, bots & power-ups — friends join your address',
  joinByIp: 'JOIN BY IP', joinByIpSub: 'Enter the server address of your friend',
  openServer: 'OPEN SERVER', serverAddress: 'SERVER ADDRESS',
  connectedTo: 'CONNECTED TO', tapCopy: 'Tap to copy', copied: 'Address copied!',
  shareAddrHint: 'Friends tap JOIN BY IP and enter this address',
  joinAddrPlaceholder: 'e.g. 192.168.1.24:3000',
  // v3.7 APK (host phone = server, works with NO internet over Wi-Fi or hotspot)
  joinAddrPlaceholderApp: 'e.g. 192.168.43.1',
  joinAddrHintApp: 'Same Wi-Fi or connected to the host\'s hotspot? Type the IP shown on the host\'s lobby screen. No internet needed.',
  shareAddrHintApp: 'Friends join your Wi-Fi or hotspot, tap JOIN BY IP and type this IP',
  mpStartingServer: 'Starting server on this phone…',
  mpHostFailedApp: 'Could not start the server on this phone. Turn Wi-Fi or hotspot on and try again',
  mpOfflineApp: 'Host not found. Check you are on the same Wi-Fi/hotspot and the IP is correct',
  mpNeedAddr: 'Type the host\'s IP first',
  // v3.8 LAN fixes: live IP, auto-discovery
  noLanIp: 'Wi-Fi / hotspot is OFF',
  lanNoIpHint: 'Turn on this phone\'s HOTSPOT (or join a Wi-Fi) — the IP appears here by itself',
  lanNoPlugin: 'Server module missing in this APK',
  lanNoPluginHint: 'Rebuild with: npm run android:sync — then Build APK again',
  lanKindHotspot: 'Hotspot', lanKindWifi: 'Wi-Fi', lanKindOther: 'LAN',
  findServers: 'SERVERS NEARBY', scanningServers: 'Searching for servers…',
  noServersFound: 'No server yet. Host must tap OPEN SERVER, and you must be on their Wi-Fi or hotspot',
  orTypeIp: 'or type the IP by hand:',
  vpnHint: 'Tip: turn OFF VPN on both phones, it blocks local Wi-Fi games',
  joinAddrHint: 'Friends on the same Wi-Fi: open this game at the host address. This server: {0}',
  joinAddrHint2: 'This device address: {0}',
  bots: 'BOTS', noBots: 'NONE',
  itemsInBoxes: 'POWER-UPS IN BOXES',
  carChoice: 'YOUR CAR', charChoice: 'YOUR CHARACTER',
  noServerFound: 'No open server found — ask your friend to open one first',
  mpOffline: 'Multiplayer server unreachable — it was restarted automatically, tap again in a few seconds',
  mpHealing: 'Multiplayer server was asleep — waking it up…',
  // settings subs (fully localized — no more hardcoded English subs)
  wheelSizeSub: 'Small / Medium / Large', autoGasSub: 'Auto-accelerate',
  invertSteerSub: 'Left ↔ Right', controlLayoutSub: 'Wheel ◀ ▶ / Buttons ▲ ▼',
  dataSub: 'Export / Import / Reset',
  lookBack: 'LOOK BACK', speedParity: 'All players race with identical speed',
  // v1.8: first-person camera + power-up toggle
  camMode: 'CAMERA', camChase: 'CHASE', camFp: 'FIRST PERSON', camSub: 'Chase view / Driver eyes',
  itemsToggle: 'POWER-UPS', itemsToggleSub: 'On / Off in races',
  // characters (title / desc / trait label / trait desc) — full FA coverage
  ch_bolt: 'The Rocket Rookie', ch_bolt_d: 'A delivery kid who upgraded from pizza bags to race karts. Never skips leg day, never brakes early.',
  ch_bolt_t: 'ROCKET START', ch_bolt_td: '+20% stronger start boost',
  ch_pip: 'The Gadget Genius', ch_pip_d: 'Half mechanic, half mischief. She built her first kart from a washing machine. It worked. Mostly.',
  ch_pip_t: 'SCRAPYARD LUCK', ch_pip_td: 'Item boxes tend to hold stronger power-ups',
  ch_moss: 'The Nature Cruiser', ch_moss_d: 'A sleepy forest spirit who somehow drifts beautifully. Smells faintly of pine and victory.',
  ch_moss_t: 'ROOTED GRIP', ch_moss_td: '-50% off-road slowdown',
  ch_tiko: 'The Drift Ape', ch_tiko_d: 'Jungle-born drift king. Communicates entirely in tire squeals and victory chest-beats.',
  ch_tiko_t: 'JUNGLE STYLE', ch_tiko_td: 'Drift charges 25% faster',
  ch_ember: 'The Flame Chaser', ch_ember_d: 'Grew up next to a volcano. Considers lava a "mild inconvenience" and boost pads a lifestyle.',
  ch_ember_t: 'HOT STREAK', ch_ember_td: 'Boost pads & turbo last +25% longer',
  ch_glacier: 'The Cold Shoulder', ch_glacier_d: 'An ice golem with a heart of gold (frozen). Bad news for anyone relying on flashy gadgets.',
  ch_glacier_t: 'COLD BLOOD', ch_glacier_td: 'Frozen & EMP time -40%',
  ch_magno: 'The Coin Collector', ch_magno_d: 'A retired factory robot with a magnetic personality - literally. Boxes just can\'t resist.',
  ch_magno_t: 'MAGNETIC PULL', ch_magno_td: 'Attract item boxes from farther away',
  ch_blocksley: 'The Iron Gentleman', ch_blocksley_d: 'A knight-turned-racer. Fights with honor, wins with bumpers. "Most rude!" - after every collision.',
  ch_blocksley_t: 'IRON BUMPER', ch_blocksley_td: '+30% knockback dealt, -20% taken',
  ch_nova: 'The Sky Runner', ch_nova_d: 'Grew up on floating islands. Treats jumps like doorways and gravity like a mild suggestion.',
  ch_nova_t: 'FEATHERFALL', ch_nova_td: 'Better air control & softer landings',
  ch_vex: 'The Midnight Racer', ch_vex_d: 'Nobody has seen Vex\'s face. Nobody has beaten Vex twice. The slipstream whispers when they pass.',
  ch_vex_t: 'SHADOW DRAFT', ch_vex_td: 'Draft/slipstream boost is 2x stronger',
};

const FA: Record<string, string> = {
  ok: 'باشه', cancel: 'لغو', back: 'بازگشت', close: 'بستن', on: 'روشن', off: 'خاموش',
  locked: 'قفل', owned: 'داری', buy: 'خرید', equip: 'انتخاب', equipped: 'انتخاب شد',
  select: 'انتخاب', selected: 'انتخاب شد', free: 'رایگان', new: 'جدید!', max: 'حداکثر',
  play: 'بازی', garage: 'گاراژ', characters: 'شخصیت‌ها', items: 'آیتم‌ها',
  shop: 'فروشگاه', settings: 'تنظیمات', mapSelection: 'انتخاب مپ',
  challenges: 'چالش‌ها', dailyRewards: 'جایزه روزانه', news: 'اخبار',
  multiplayer: 'چندنفره', career: 'مسیر حرفه‌ای', quickRace: 'مسابقه سریع',
  level: 'سطح', xp: 'امتیاز',
  raceExplore: 'مسابقه • کاوش • جمع‌آوری',
  tapToStart: 'برای شروع لمس کن',
  chooseMode: 'حالت را انتخاب کن', careerDesc: '۶۰ مرحله دست‌ساز پر از چالش',
  quickDesc: 'مسابقه فوری روی هر مپی', mpDesc: 'بازی با دوستان روی وای‌فای',
  selectLevel: 'انتخاب مرحله', laps: 'دور', difficulty: 'درجه سختی',
  objective: 'هدف مرحله', best: 'بهترین', stars: 'ستاره',
  easy: 'آسان', normal: 'معمولی', hard: 'سخت', extreme: 'وحشیانه',
  special: 'ویژه', boss: 'باوس',
  obj_finish1: 'اول شو', obj_finish3: 'جزو ۳ نفر اول شو', obj_time: '{0} ثانیه — زمان را بزن!',
  obj_drift: 'مجموعاً {0} ثانیه دریفت بزن', obj_items: 'از {0} قدرت استفاده کن',
  obj_survive: 'از خطرها جان سالم ببر', obj_nofall: 'بدون سقوط ببر', obj_clean: 'بدون تصادف ببر',
  // قانون‌های ویژه هر مرحله
  mod_none: 'قانون استاندارد',
  mod_night: 'مسابقه شبانه', mod_night_d: 'چراغ‌ها روشن — دنیا تاریک می‌شود',
  mod_lowgrip: 'جاده یخی', mod_lowgrip_d: 'آسفالت لیز است — زود ترمز بگیر!',
  mod_turbostart: 'استارت توربو', mod_turbostart_d: 'لحظه شروع مسابقه بوست رایگان بگیر',
  mod_itemstorm: 'طوفان آیتم', mod_itemstorm_d: 'جعبه‌های قدرت دو برابر شده‌اند',
  mod_noitems: 'مهارت خالص', mod_noitems_d: 'بدون قدرت‌ها — فقط رانندگی',
  mod_fog: 'مه غلیظ', mod_fog_d: 'دید کم — به مینی‌مپ اعتماد کن',
  mod_boss: 'مسابقه باوس', mod_boss_d: 'یک حریف با ماشین کاملاً ارتقا یافته',
  mod_gems: 'دو جواهری', mod_gems_d: 'جایزه اضافه جواهر برای ۳ نفر اول',
  mod_veteran: 'حریف‌های حرفه‌ای', mod_veteran_d: 'حریف‌ها امروز عصبانی‌اند',
  mod_hazard: 'منطقه خطر', mod_hazard_d: 'پیست پر از خطر است',
  pos: 'جای', lap: 'دور', wrongWay: 'مسیر اشتباه!', finalLap: 'دور آخر!',
  go: 'برو!', countdown3: '۳', countdown2: '۲', countdown1: '۱',
  paused: 'توقف', resume: 'ادامه', restart: 'شروع دوباره', quit: 'خروج از مسابقه',
  drift: 'دریفت', gas: 'گاز', brake: 'ترمز',
  raceFinished: 'مسابقه تمام شد', youWin: 'پیروزی!', youLose: 'پایان مسابقه',
  rewards: 'جوایز', coins: 'سکه', gems: 'جواهر', parts: 'قطعات',
  nextRace: 'مسابقه بعدی', replay: 'دوباره', toMenu: 'منو',
  newRecord: 'رکورد جدید!', missionComplete: 'ماموریت کامل شد!', missionFailed: 'ماموریت ناموفق',
  bestTime: 'بهترین زمان', time: 'زمان', retry: 'تلاش دوباره',
  stats: 'مشخصات', customize: 'شخصی‌سازی', cars: 'ماشین‌ها',
  speed: 'سرعت', accel: 'شتاب', handling: 'فرمان‌پذیری', driftStat: 'دریفت',
  weight: 'وزن', boost: 'بوست', defense: 'دفاع',
  paint: 'رنگ', wheels: 'چرخ‌ها', spoiler: 'بال عقب', decals: 'طرح بدنه',
  exhaust: 'اگزوز', boostFx: 'جلوه بوست', upgrade: 'ارتقا',
  underglow: 'نور زیر ماشین', underglowHint: 'نور نئونی زیر ماشینت — فقط شب روشن می‌شود (خودکار در تاریکی) • همهٔ ماشین‌ها دارند؛ یک رنگ انتخاب کن یا روی خودکار بگذار',
  none: 'خاموش',
  upgradeCost: 'ارتقا ({0})', maxed: 'کاملاً ارتقا یافته',
  // ورکشاپ (تعمیرگاه — آپدیت بزرگ گاراژ)
  workshop: 'ورکشاپ', workshopSub: 'ماشینت را تیکه تیکه تیون کن',
  w_engine: 'موتور', w_engine_d: 'سرعت نهایی',
  w_turbo: 'توربو', w_turbo_d: 'قدرت و زمان بوست',
  w_tires: 'لاستیک', w_tires_d: 'چسبندگی و فرمان‌پذیری',
  w_driftkit: 'کیت دریفت', w_driftkit_d: 'سرعت شارژ دریفت',
  w_armor: 'زره', w_armor_d: 'وزن و مقاومت به ضربه',
  w_buildLvl: 'دون سطح', w_next: 'بعدی', w_unlockHint: 'برای تیون بیشتر به سطح {0} برس',
  buildBonus: 'پاداش تیون کامل: +۴٪ همه مشخصه‌ها',
  charSelect: 'شخصیت‌ها', ability: 'قابلیت ویژه',
  shopTitle: 'فروشگاه', dailyOffers: 'پیشنهاد روزانه', bundles: 'پکیج‌ها',
  soldOut: 'تمام شد', notEnough: 'موجودی کافی نیست', purchased: 'خریده شد!',
  bundle_starter: 'پکیج شروع', bundle_starter_d: '۸ قطعه + ۱۰ جواهر',
  bundle_parts: 'جعبه قطعات', bundle_parts_d: '۱۵ قطعه ارتقا',
  bundle_gem: 'گنج جواهر', bundle_gem_d: '۵٬۰۰۰ سکه + ۱۰ قطعه',
  claim: 'دریافت', claimed: 'دریافت شد', comeBack: 'فردا دوباره بیا!',
  day: 'روز', nextReward: 'جایزه بعدی تا',
  dailyTasks: 'کارهای روزانه', rewards2: 'جوایز', collect: 'دریافت همه',
  ch_win1: 'یک مسابقه ببر', ch_win3: '۳ مسابقه ببر', ch_drift20: '۲۰ ثانیه دریفت بزن',
  ch_coins50: '۷۵۰ سکه از مسابقه‌ها به دست بیاور', ch_items5: '۵ بار قدرت استفاده کن', ch_race2: '۲ مسابقه تمام کن',
  ch_stars2: '۲ ستاره بگیر', ch_mp1: 'یک مسابقه چندنفره بازی کن', ch_jump10: '۱۰ بار بپر',
  mpTitle: 'چندنفره محلی (وای‌فای)', createRoom: 'ساخت اتاق', joinRoom: 'پیوستن به اتاق',
  roomCode: 'کد اتاق', enterCode: 'کد اتاق را وارد کن...', join: 'پیوستن',
  players: 'بازیکنان', ready: 'آماده', notReady: 'آماده نیست', startRace: 'شروع مسابقه',
  waitingHost: 'منتظر شروع توسط میزبان...', connected: 'وصل شد!',
  connecting: 'در حال اتصال...', connectionLost: 'اتصال قطع شد!',
  hostLeft: 'میزبان رفت - میزبان جدید: {0}', playerJoined: '{0} وارد شد!', playerLeft: '{0} خارج شد',
  mpReconnecting: 'اتصال قطع شد — در حال وصل شدن دوباره', mpReconnected: 'دوباره وصل شدی!', mpPeerLost: 'اتصال {0} قطع شد…', mpPeerBack: '{0} برگشت',
  chooseTrack: 'انتخاب پیست', yourIp: 'این کد را به دوستانت بده',
  mpNeedsServer: 'چندنفره به سرور بازی نیاز دارد. راهنما را ببین.',
  scanning: 'در جستجوی اتاق...', youAreHost: 'تو میزبان هستی',
  raceInProgress: 'مسابقه در حال اجراست',
  settingsTitle: 'تنظیمات', graphics: 'گرافیک', sound: 'صدا',
  music: 'موسیقی', sfx: 'افکت', master: 'صدای کلی', vibration: 'لرزش',
  sensitivity: 'حساسیت فرمان', controlLayout: 'حالت فرمان', wheelSize: 'اندازه فرمان',
  wheel: 'فرمان', buttons: 'دکمه‌ای', tilt: 'کج‌کردن',
  language: 'زبان', data: 'داده‌ها', showFps: 'نمایش FPS',
  exportData: 'خروجی ذخیره', importData: 'بازیابی ذخیره', resetData: 'پاک کردن پیشرفت',
  resetConfirm: 'همه پیشرفت پاک شود؟ این کار برگشت‌پذیر نیست!',
  low: 'کم', medium: 'متوسط', high: 'زیاد', ultra: 'فوق‌العاده',
  item_boost: 'نیترو', item_shield: 'سپر', item_rocket: 'موشک', item_lightning: 'آذرخش',
  item_ice: 'یخ', item_trap: 'لکه روغن', item_mine: 'مین', item_magnet: 'آهنربا',
  item_emp: 'ضربه مغناطیسی', item_giant: 'حالت هیولا', item_ghost: 'روح', item_jump: 'مین فنری',
  // توضیح آیتم‌ها (نسخهٔ ۱.۹: راهنمای آیتم‌ها فارسی شد)
  item_boost_d: 'توربوی آنی — اگزوز غرش می‌کند و ناگهان جلو می‌پری.',
  item_shield_d: 'یک حباب انرژی آبی. ضربهٔ بعدی را دفع می‌کند — و موشکِ در راه را هم برمی‌گرداند!',
  item_rocket_d: 'موشکی هوشمند که تعقیب جلویی‌ها می‌کند. صدای بوق‌های هشدار را بشنو — اگر برای تو بیب‌بیب کرد یعنی می‌خواهد به تو بخورد! با نگه‌داشتن دکمهٔ نگاه به عقب، به عقب‌ترین شلیک می‌شود.',
  item_lightning_d: 'طوفان آبی: سه میدان بزرگ الکتریکی، یکی‌یکی (یک… دو… سه…) جلوی مسیر نفر اول ظاهر می‌شوند، هر کدام با صدای خفن رعد و برق. هر کس وارد میدان شود برق‌گرفته می‌شود — دمیج خیلی زیاد — و همان میدان ناپدید می‌شود. میدان‌ها بعد از ۱۲ ثانیه خودشان از بین می‌روند.',
  item_ice_d: 'تراشهٔ یخی که تعقیب جلویی‌ها می‌کند و او را داخل مکعب یخ قفل می‌کند.',
  item_trap_d: 'پشت سرت لکهٔ روغن لیز خورنده می‌اندازد. حریف‌هایی که رویش بروند منحرف می‌شوند.',
  item_mine_d: 'پشت ماشینت مین کاری می‌کند. هر کس رویش برود منفجر می‌شود — حتی خود تو! به چراغ چشمک‌زن قرمزش نگاه کن!',
  item_magnet_d: 'جعبه‌های دور را به سمتت می‌کشد • آخر مسابقه ۶۰ سکهٔ اضافه می‌دهد. میدانش موشک را هم دفع می‌کند!',
  item_emp_d: 'موج ضربه‌ای بنفش که هرکس نزدیکت باشد را از کار می‌اندازد.',
  item_giant_d: 'حالت هیولا: غول‌پیکر می‌شوی، همه را از سر راه پرت می‌کنی کنار، سلاح‌ها دو برابر بزرگ شلیک می‌شوند و نصف دمیج می‌گیری.',
  item_ghost_d: '۵ ثانیه شبح می‌شوی: موشک، مین و آذرخش از وجودت رد می‌شود و از لای حریف‌ها رد می‌شوی.',
  item_jump_d: 'یک صفحهٔ چوبی کف جاده پشت سرت می‌کارد. هر کس از رویش رد شود فنرِ زیر چوب آزاد می‌شود و ماشینش را به هوا پرت می‌کند و دمیج سنگین می‌خورد. منفجر نمی‌شود و بعد از مسلح شدن خودت را هم می‌گیرد!',
  item_tnt: 'تی‌ان‌تی', item_banana: 'پوست موز', item_minecart: 'واگن معدن',
  item_tnt_d: 'یک بلوک TNT روشن پشت سرت می‌گذارد. فتیله‌اش همین‌طور می‌سوزد و همان لحظه که ماشینی به آن برسد منفجر می‌شود. انفجار بزرگ، ماشین‌ها را به هوا پرت می‌کند.',
  item_banana_d: 'پوست موز را روی جاده می‌اندازد. اولین کسی که رویش برود سُر می‌خورد و می‌چرخد.',
  item_minecart_d: 'یک واگن معدن فراری احضار می‌کند که روی ریل خودش در مسیر حرکت می‌کند، نزدیک‌ترین حریف جلویی را شکار می‌کند و از جاده بیرونش می‌اندازد.',
  breakdown: 'خراب شد!', repaired: 'تعمیر شد — برگشت به مسابقه!',
  carTier: 'رده',
  carWrecked: 'ماشین نابود شد! داریم تعمیرش می‌کنیم…',
  missileWarn: 'موشک داره میاد!',
  // ویرایشگر چیدمان دکمه‌ها (نسخهٔ ۱.۱۰)
  hudLayout: 'چیدمان دکمه‌ها',
  hudLayoutSub: 'جابه‌جایی و بزرگ/کوچک کردن همهٔ دکمه‌های صفحه',
  hudLayoutEdit: 'ویرایش چیدمان',
  hudLayoutHint: 'برای جابه‌جایی، دکمه را بکش — با ＋ / − بزرگ و کوچکش کن',
  hudLayoutReset: 'بازنشانی',
  hudLayoutDone: 'تمام',
  hudLayoutSaved: 'چیدمان ذخیره شد',
  // نسخهٔ ۱.۲۲ — پریست چیدمان (ساده / معمولی) + سرعت‌سنج قابل جابه‌جایی
  hudPreset: 'چیدمان صفحه',
  hudPresetSub: 'نسخهٔ ساده همه‌چیز را جمع‌وجور می‌کند — سرعت‌سنج زیر خانه‌های آیتم می‌رود',
  hudSimple: 'ساده',
  hudNormal: 'معمولی',
  hudSimpleToast: 'چیدمان ساده (پیش‌فرض)',
  hudNormalToast: 'چیدمان معمولی',
  layoutPedals: 'گاز / ترمز', layoutSteer: 'راست / چپ', layoutWheel: 'ناحیه فرمان',
  layoutDrift: 'دریفت', layoutSlots: 'قدرت‌ها', layoutHearts: 'نوار جون',
  layoutLook: 'نگاه به عقب', layoutPause: 'توقف', layoutMeter: 'نوار دریفت',
  layoutSpeedo: 'سرعت‌سنج',
  // نسخهٔ ۱.۱۱ — هر دکمه جداگانه + فهرست اسم صداها
  layoutGas: 'گاز', layoutBrake: 'ترمز', layoutLeft: 'چپ ◀', layoutRight: 'راست ▶',
  layoutSlot1: 'قدرت ۱', layoutSlot2: 'قدرت ۲', layoutSlot3: 'قدرت ۳',
  layoutLight: 'چراغ جلو',
  soundList: 'فهرست صداها',
  soundListSub: 'همهٔ صداهای بازی با اسم — بزن تا بشنوی',
  glowAuto: 'خودکار (نئون پیش‌فرض)',
  lobbyCustomize: 'شخصی‌سازی ماشین', lobbyHintHostCars: 'اینجا می‌توانی از ماشین‌های بازشده‌ی میزبان هم استفاده کنی',
  theme_grass: 'دره آفتابی', theme_castle: 'دژ سنگی', theme_desert: 'تپه‌های آفتاب‌سوخته',
  theme_snow: 'قله‌های یخی', theme_volcano: 'هسته گدازه', theme_cave: 'غارهای پژواک',
  theme_sky: 'باغ‌های آسمانی', theme_city: 'شهر نئون', theme_crashcity: 'کراش‌سیتی', theme_ruins: 'ویرانه‌های گمشده',
  theme_jungle: 'جنگل وحشی', theme_mccity: 'شهر بلوک‌تک', theme_megaramp: 'مگا رمپ', theme_candy: 'سرزمین آبنبات', theme_galaxy: 'کهکشان ستاره‌ها', theme_dragon: 'معبد اژدها', theme_royal: 'شهر طلایی سلطنتی',
  cls_balanced: 'متعادل', cls_speed: 'سرعتی', cls_drift: 'دریفتی',
  cls_heavy: 'سنگین', cls_accel: 'شتاب‌زده',
  carUnlockToast: '{0} حالا در گاراژ موجوده!',
  carReqLevel: 'باز می‌شود در سطح {0}',
  loading: 'در حال بارگذاری', tip: 'نکته', version: 'نسخه',
  generatingTrack: 'در حال ساخت پیست…', buildingWorld: 'در حال ساختن دنیا…', paintingSky: 'در حال رنگ‌آمیزی آسمان…',
  driftBoostReady: 'مینی‌توربو!', ultraTurbo: 'توربوی فوق‌العاده!',
  recovered: 'نجات یافتی!',
  invertSteer: 'برعکس کردن فرمون',
  autoGas: 'گاز خودکار',
  coinsRace: 'سکه', position: 'جایگاه',
  unlockAtLevel: 'باز می‌شود در سطح {0}', unlockLevelN: 'برای خرید به سطح {0} برس',
  beat: 'شکست دادن', sec: 'ثانیه', no: 'خیر', yes: 'بله',
  howToPlay: 'طرز بازی', controlsInfo: 'با فرمان بپیچ • گاز را نگه دار • در پیچ‌ها دریفت بگیر تا مینی‌توربو شارژ شود • دکمه قدرت را بزن',
  profile: 'پروفایل', editName: 'برای تغییر اسم لمس کن',
  winStreak: 'بردهای پیاپی', races: 'مسابقه', wins: 'برد',
  worldRecord: 'رکورد شخصی', finish: 'پایان',
  newsTitle: 'آخرین اخبار',
  newsBody: 'فصل ۲ شروع شد! ۶۰ مرحله بازسازی‌شده با مسابقه شبانه، جاده یخی، طوفان آیتم و حریف‌های باوس. ۶ ماشین اسپرت جدید در گاراژ منتظرت است — سطحت را بالا ببر تا همه را باز کنی!',
  eventTitle: 'ایونت فصل ۲', eventDesc: 'فصل ماشین‌های اسپرت! ماشین‌های تازه، قانون‌های تازه مرحله‌ها و پیست‌های بزرگ‌تر.',
  bootSub: 'مسابقه پیکسلی آرکید',
  bootTip1: 'در پیچ‌ها دریفت را نگه دار تا مینی‌توربو شارژ شود!',
  bootTip2: 'جرقه طلایی = توربوی فوق‌العاده. دریفت را رها کن تا شلیک شود!',
  bootTip3: 'بازیکن‌های عقب‌تر قدرت‌های قوی‌تر می‌گیرند. منصفانه و جذاب!',
  bootTip4: 'ماشینت را در ورکشاپ تیون کن تا سریع‌تر شود!',
  bootTip5: 'با دوستان روی وای‌فای بازی کن — تا ۶ نفر!',
  start: 'شروع',
  becomeServer: 'میزبان (سرور) شو', becomeServerSub: 'مپ و بات‌ها و قدرت‌ها را انتخاب کن — بقیه با آدرس تو میان',
  joinByIp: 'پیوستن با آی‌پی', joinByIpSub: 'آدرس سرور دوستت را وارد کن',
  openServer: 'باز کردن سرور', serverAddress: 'آدرس سرور',
  connectedTo: 'وصل شدی به', tapCopy: 'برای کپی لمس کن', copied: 'آدرس کپی شد!',
  shareAddrHint: 'دوستانت «پیوستن با آی‌پی» را بزنند و این آدرس را وارد کنند',
  joinAddrPlaceholder: 'مثلاً 192.168.1.24:3000',
  joinAddrPlaceholderApp: 'مثلاً 192.168.43.1',
  joinAddrHintApp: 'روی همان وای‌فای هستی یا به هات‌اسپات میزبان وصلی؟ آی‌پی‌ای که روی صفحهٔ لابی میزبان نوشته را وارد کن. اینترنت لازم نیست.',
  shareAddrHintApp: 'دوستانت به وای‌فای یا هات‌اسپات تو وصل شوند، «پیوستن با آی‌پی» را بزنند و این آی‌پی را وارد کنند',
  mpStartingServer: 'در حال روشن کردن سرور روی این گوشی…',
  mpHostFailedApp: 'سرور روی این گوشی روشن نشد؛ وای‌فای یا هات‌اسپات را روشن کن و دوباره بزن',
  mpOfflineApp: 'میزبان پیدا نشد؛ مطمئن شو روی همان وای‌فای/هات‌اسپات هستید و آی‌پی درست است',
  mpNeedAddr: 'اول آی‌پی میزبان را وارد کن',
  // v3.8 LAN fixes: live IP, auto-discovery
  noLanIp: 'وای‌فای / هات‌اسپات خاموشه',
  lanNoIpHint: 'هات‌اسپات همین گوشی رو روشن کن (یا به یه وای‌فای وصل شو) — آی‌پی خودش همین‌جا میاد',
  lanNoPlugin: 'ماژول سرور داخل این APK نیست',
  lanNoPluginHint: 'دوباره بیلد بگیر: npm run android:sync بعد Build APK',
  lanKindHotspot: 'هات‌اسپات', lanKindWifi: 'وای‌فای', lanKindOther: 'شبکه',
  findServers: 'سرورهای اطراف', scanningServers: 'در حال پیدا کردن سرور…',
  noServersFound: 'هنوز سروری پیدا نشد. میزبان باید «باز کردن سرور» رو بزنه و تو باید به وای‌فای یا هات‌اسپاتش وصل باشی',
  orTypeIp: 'یا آی‌پی رو دستی وارد کن:',
  vpnHint: 'نکته: فیلترشکن (VPN) رو روی هر دو گوشی خاموش کنید؛ جلوی بازی وای‌فای رو می‌گیره',
  joinAddrHint: 'دوستان روی همان وای‌فای: بازی را با آدرس میزبان باز کنند. این سرور: {0}',
  joinAddrHint2: 'آدرس این گوشی: {0}',
  bots: 'بات', noBots: 'بدون بات',
  itemsInBoxes: 'قدرت‌های داخل جعبه',
  mpOffline: 'سرور چندنفره در دسترس نبود — خودکار دوباره روشن شد؛ چند ثانیه دیگر دوباره امتحان کن',
  mpHealing: 'سرور چندنفره خاموش بود — در حال روشن کردن…',
  carChoice: 'ماشین تو', charChoice: 'شخصیت تو',
  noServerFound: 'هیچ سرور بازی پیدا نشد — اول دوستت یک سرور باز کند',
  // تنظیمات — زیرنویس‌ها کاملاً فارسی شدند
  wheelSizeSub: 'کوچک / متوسط / بزرگ', autoGasSub: 'خودش گاز می‌دهد',
  invertSteerSub: 'چپ ↔ راست', controlLayoutSub: 'فرمان ◀ ▶ / دکمه ▲ ▼',
  dataSub: 'خروجی / بازیابی / پاک‌سازی',
  lookBack: 'نگاه به عقب', speedParity: 'همه بازیکن‌ها با سرعت یکسان مسابقه می‌دهند',
  // v1.8: دوربین اول‌شخص + کلید روشن/خاموش قدرت‌ها
  camMode: 'دوربین', camChase: 'تعقیبی', camFp: 'اول شخص', camSub: 'دید تعقیبی / چشم راننده',
  itemsToggle: 'قدرت‌ها', itemsToggleSub: 'روشن / خاموش در مسابقه',
  // شخصیت‌ها — عنوان / توضیح / قابلیت
  ch_bolt: 'تازه‌کار موشکی', ch_bolt_d: 'پسرک سفارش‌رسان که از کیف پیتزا به کارت مسابقه رسید. هیچ‌وقت تمرین پا را جا نمی‌اندازد و هیچ‌وقت زود ترمز نمی‌گیرد.',
  ch_bolt_t: 'استارت موشکی', ch_bolt_td: 'بوست استارت ۲۰٪ قوی‌تر',
  ch_pip: 'نابغه ابزارها', ch_pip_d: 'نیمه مکانیک، نیمه شیطان. اولین کارتش را از یک ماشین لباسشویی ساخت. کار کرد. تقریباً.',
  ch_pip_t: 'شانس قراضه‌ها', ch_pip_td: 'جعبه‌های آیتم معمولاً قدرت‌های قوی‌تری دارند',
  ch_moss: 'گردش‌گر طبیعت', ch_moss_d: 'روح خواب‌آلود جنگل که عجیب زیبا دریفت می‌زند. کمی بوی کاج و پیروزی می‌دهد.',
  ch_moss_t: 'چسبندگی ریشه‌ای', ch_moss_td: 'کندی بیرون از جاده ۵۰٪ کمتر',
  ch_tiko: 'میمون دریفت‌باز', ch_tiko_d: 'پادشاه دریفتِ جنگل. فقط با جیغ لاستیک و سینه‌کوبی پیروزی حرف می‌زند.',
  ch_tiko_t: 'سبک جنگلی', ch_tiko_td: 'دریفت ۲۵٪ سریع‌تر شارژ می‌شود',
  ch_ember: 'تعقیب‌کننده شعله', ch_ember_d: 'کنار آتشفشان بزرگ شده. گدازه را «مشکل کوچکی» می‌داند و رمپ بوست سبک زندگی اوست.',
  ch_ember_t: 'خط آتش', ch_ember_td: 'رمپ بوست و توربو ۲۵٪ بیشتر دوام می‌آورند',
  ch_glacier: 'یخ‌مرد سردمزاج', ch_glacier_d: 'گولم یخی با قلب طلایی (البته یخ‌زده). خبر بد برای هرکسی که به اسباب‌بازی‌های برقی دل بسته.',
  ch_glacier_t: 'خونسرد', ch_glacier_td: 'زمان یخ‌زدگی و امپ ۴۰٪ کمتر',
  ch_magno: 'سکه‌جمع‌کن', ch_magno_d: 'ربات بازنشستهٔ کارخانه با شخصیت آهنربایی — واقعاً! جعبه‌ها نمی‌توانند مقاومت کنند.',
  ch_magno_t: 'کشش آهنربایی', ch_magno_td: 'جعبه‌های آیتم از دورتر به سمتت کشیده می‌شوند',
  ch_blocksley: 'جنتلمن آهنی', ch_blocksley_d: 'شوالیه‌ای که مسابقه‌دهنده شد. با شرافت می‌جنگد و با سپر می‌برد. «چه بی‌ادبانه!» — بعد از هر تصادف.',
  ch_blocksley_t: 'سپر آهنی', ch_blocksley_td: '۳۰٪ ضربه بیشتر، ۲۰٪ ضربه کمتر می‌گیرد',
  ch_nova: 'دونده آسمان', ch_nova_d: 'روی جزیره‌های شناور بزرگ شده. پرش‌ها را مثل در می‌بیند و جاذبه را یک پیشنهاد ملایم.',
  ch_nova_t: 'پر پرنده', ch_nova_td: 'کنترل هوایی بهتر و فرود نرم‌تر',
  ch_vex: 'مسابقه‌دهنده نیمه‌شب', ch_vex_d: 'هیچ‌کس صورت وکس را ندیده و هیچ‌کس دو بار از او نبرده. وقتی رد می‌شود، باد نجوا می‌کند.',
  ch_vex_t: 'سایه‌باد', ch_vex_td: 'بوست بادِ پشت‌سر ۲ برابر قوی‌تر',
};

/** v2.0: extra string packs registered from other modules */
export function extendLang(en: Record<string, string>, fa: Record<string, string>) {
  Object.assign(EN, en);
  Object.assign(FA, fa);
}

export type Lang = 'en' | 'fa';
let cur: Lang = 'fa';   // Persian is the DEFAULT (user request)

export function setLang(l: Lang) { cur = l === 'en' ? 'en' : 'fa'; }
export function getLang(): Lang { return cur; }

export function t(key: string, ...args: (string | number)[]): string {
  const dict = cur === 'fa' ? FA : EN;
  let s = dict[key] ?? EN[key] ?? key;
  for (let i = 0; i < args.length; i++) s = s.replace(`{${i}}`, String(args[i]));
  return s;
}

export function isRTL(): boolean { return cur === 'fa'; }

// ---------- Persian digits ----------
const FA_DIGITS = ['۰', '۱', '۲', '۳', '۴', '۵', '۶', '۷', '۸', '۹'];
/** Convert latin digits inside a string to Persian digits (FA mode only) */
export function dig(s: string | number): string {
  const str = String(s);
  if (cur !== 'fa') return str;
  return str.replace(/[0-9]/g, d => FA_DIGITS[Number(d)]);
}
